version: '3.8'

services:
  web:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/:/usr/src/src/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sukunat_db_user
      - POSTGRES_PASSWORD=sukunat_db_password
      - POSTGRES_DB=sukunat_db

  redis:
    image: redis:6.2.6-alpine  # Add a Redis service for the message broker

  celery_worker:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: celery -A config worker --loglevel=info
    volumes:
      - ./src/:/usr/src/src/
    env_file:
      - .env.dev
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: celery -A config beat --loglevel=info
    volumes:
      - ./src/:/usr/src/src/
    env_file:
      - .env.dev
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
