# Generated by Django 5.0.2 on 2024-05-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code_en',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='code_ru',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='code_uz',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='code_uz_cyrl',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_uz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_uz_cyrl',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
