# Generated by Django 5.0.2 on 2024-05-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videocourses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="videocourse",
            name="lang",
            field=models.CharField(default="ru", max_length=10),
            preserve_default=False,
        ),
    ]
