# Generated by Django 5.0.2 on 2024-05-10 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("videocourses", "0002_videocourse_lang"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="videocourse",
            options={"ordering": ["-created_at"]},
        ),
    ]
