# Generated by Django 5.0.2 on 2024-06-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videocourses", "0003_alter_videocourse_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="videos/"),
        ),
        migrations.AddField(
            model_name="video",
            name="youtube_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
