# Generated by Django 5.0.2 on 2024-05-10 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-created_at"]},
        ),
    ]
