# Generated by Django 5.0.2 on 2024-05-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_article_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.FileField(
                blank=True, null=True, upload_to="articles/category/"
            ),
        ),
    ]
