# Generated by Django 5.0.2 on 2024-06-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0005_alter_category_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="read_time",
            field=models.IntegerField(default=0),
        ),
    ]
