# Generated by Django 5.0.2 on 2024-06-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0006_article_read_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
