# Generated by Django 5.0.2 on 2024-07-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="color",
            field=models.CharField(default="#81C784", max_length=7),
        ),
    ]
