# Generated by Django 5.0.2 on 2024-06-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sos", "0002_trackingsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackingsession",
            name="initial_latitude",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trackingsession",
            name="initial_longitude",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
