# Generated by Django 5.0.2 on 2024-05-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="posts", to="forum.tag"
            ),
        ),
    ]
